---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: sugardonblog
build:
  artifacts:
    - image: sugardonblog
      context: .
      buildpacks:
        builder: "paketobuildpacks/builder-jammy-base:0.4.388"
deploy:
  helm:
    releases:
      - name: nextjs-sugardonblog
        repo: "https://helm.sugardon.com"
        remoteChart: "nextjs"
        version: 0.0.3
        #https://skaffold.dev/docs/pipeline-stages/deployers/helm/#helm-strategy-split-repository-and-tag
        setValueTemplates:
          image:
            repository: "{{.IMAGE_REPO_sugardonblog}}"
            tag: "{{.IMAGE_TAG_sugardonblog}}@{{.IMAGE_DIGEST_sugardonblog}}"
