---
# https://github.com/adambkaplan/devsecops-shipwright-tekton
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sugardonblog-build
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
          storageClassName: tekton-dev-sc
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    workspaces:
      - name: source
    params:
      - name: repo_url
      - name: revision
    tasks:
      - name: git-clone
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
      - name: build
        runAfter: [git-clone]
        params:
          - name: shp-source-url
            value: $(params.repo_url)
          - name: shp-source-revision
            value: $(params.revision)
          - name: shp-output-url
            value: "docker.io/sugardon/sugardonblog"
        taskSpec:
          apiVersion: shipwright.io/v1alpha1
          kind: Build
          spec:
            source:
              url: $(params.shp-source-url)
              revision: $(params.shp-source-revision)
            strategy:
              name: buildpacks-v3
              kind: ClusterBuildStrategy
            output:
              image: $(params.shp-output-url):$(params.shp-source-revision)
              credentials:
                name: sugardon-dockerhub-secret
