---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sugardonblog-pull-request-test
  namespace: tekton-cicd
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "[git-clone]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
spec:
  params:
    - name: greet
      value: "Hello from Sugardonblog"
  pipelineRef:
    name: hello-world
  serviceAccountName: build-bot
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        # https://github.com/tektoncd/pipeline/blob/main/docs/workspaces.md#volumeclaimtemplate
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: tekton-dev-sc
