---
# https://docs.github.com/ja/actions/guides/building-and-testing-nodejs
name: Node.js CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      # https://docs.github.com/ja/actions/guides/building-and-testing-nodejs#example-caching-dependencies
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      # https://docs.github.com/ja/actions/guides/building-and-testing-nodejs#example-using-yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: eslint
        run: yarn lint
      - name: prettier
        run: |
          yarn format
          git diff --exit-code

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test:ci
