---
name: e2e test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-test:
    name: e2e test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      # setup node
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      # https://playwright.dev/docs/ci-intro#github-actions
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # setup kubernetes
      - name: start minikube
        uses: medyagh/setup-minikube@master
        with:
          kubernetes-version: v1.23.7
      - name: setup
        run: |
          ./.devcontainer/setup.sh
      - name: skaffold production
        run: |
          skaffold run --status-check=true
      # prepare test
      - name: setup blog for test
        run: |
          kubectl expose service nextjs-sugardonblog --type=NodePort --port=8080 --name=nextjs-sugardonblog-test
          export PLAYWRIGHT_BASE_URL=$(minikube service nextjs-sugardonblog-test --url=true)
          curl --retry 10 --retry-connrefused $PLAYWRIGHT_BASE_URL -i
      # execute test
      - name: run test
        run: |
          yarn test:e2e
