---
# https://docs.github.com/ja/actions/guides/building-and-testing-nodejs
name: Node.js CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      # TODO: Cache
      # https://docs.github.com/ja/actions/guides/building-and-testing-nodejs#example-caching-dependencies
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      # https://docs.github.com/ja/actions/guides/building-and-testing-nodejs#example-using-yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: eslint
        run: yarn lint

      - name: prettier
        run: |
          yarn format
          git diff --exit-code
